name: CI
# TODO:
# * deploy install artefacts
# * common actions?
# * hardened buildflags
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CLAZY_CHECKS: "level1"

jobs:
  build:
    continue-on-error: true
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        compiler:
          - gcc
          #- clang TODO!!!
        container:
          - fedora-qt5:32
    runs-on: ubuntu-latest
    container:
      image: schnitzeltony/${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          BASEPATH=`pwd`
          mkdir -p "build-${{ matrix.compiler }}"
          mkdir -p "install/${{ matrix.container }}-${{ matrix.compiler }}"
          cd "build-${{ matrix.compiler }}"
          if [ "${{ matrix.compiler }}" == "clang" ]; then
            export CC=clang
            #export CXX=clang++
            export CXX=clazy
          fi
          # configure
          cmake .. \
            -DCMAKE_PREFIX_PATH="$BASEPATH/install/usr;/usr" \
            -DCMAKE_INSTALL_PREFIX:PATH="$BASEPATH/install/usr" \
            -DCMAKE_INSTALL_SYSCONFDIR="$BASEPATH/install/etc" \
            -DfirstBuild=ON
          # compile / install
          make -j $(getconf _NPROCESSORS_ONLN)

